# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0006_auto_20170521_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
